# Generated by Django 4.0.10 on 2023-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Test product', max_length=120),
            preserve_default=False,
        ),
    ]
