# Generated by Django 4.2.1 on 2023-05-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(default="cover.png", upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="user.png", upload_to=""),
        ),
    ]
